### PR TITLE
Call callback only once (even on error)

### LINKED ISSUE #46: Double call callback
Here: https://github.com/A/superagent-mocker/blob/master/index.js#L98

Such code:

```js

try {
    // ...
    // Code code code
    // ...

    // call 1
    cb && cb(error, null);
  } else {
    cb && cb(null, response);
  }
} catch (ex) {
  // call 2
  cb && cb(ex, null);
}

```
If you will try to use it with `mocha` and `expect` you will get **callback doublecall**, trying to assert in callback.

If this repo is alive - I could send a test case (not ready right now), and, probably, a PR

### PR DESCRIPTION
**Pull request by maxkoryukov**
fix A/superagent-mocker#46

based on blogpost: http://joseoncode.com/2013/12/27/case-of-double-callbacks/

### CODE REVIEW

**Comment by maxkoryukov** [comment]
based on story: http://joseoncode.com/2013/12/27/case-of-double-callbacks/

**Comment by tbranyen** [comment]
Looks good to me!

**Comment by tbranyen** [comment]
Thanks for the fix @maxkoryukov

**Comment by maxkoryukov** [comment]
@tbranyen , plz, tell me, when the package on NPM will be updated? I want to switch from git-dependency  to NPM-dep (you know - it is much more convenient)

**Comment by tbranyen** [comment]
I understand, I'll try and push it out tomorrow.

**Comment by maxkoryukov** [comment]
@tbranyen , NPM still keeping `0.5.2`... :cry:

**Comment by maxkoryukov** [comment]
@tbranyen , LOOK MA)) still `0.5.2` :open_hands:

**Comment by maxkoryukov** [comment]
Hello :walking_man: Are there anybody out there;) @tbranyen , plz upgrade NPM

**Pull request merged**
