### PR TITLE
Extend functionality

### PR DESCRIPTION
**Pull request by ikhilko**
- added support of "patch" method;
- added clearRoute method that remove registered before route by method and url;
- added unmock method (rollback patches in superagent);
- fixed contexts when called wrapped function.

### CODE REVIEW

**Comment by A** [comment]
@ikhilko Wow! awesome! Please update docs in the readme and I'll merge and publish this pull request :D

**Comment by ikhilko** [comment]
@shuvalov-anton  done!)

**Comment by A** [comment]
Great! Thank you!

**Comment by A** [comment]
`superagent-mocker@0.3.0` landed on the npm :D

**Pull request merged**
