### PR TITLE
Add a method to clear all registered handlers.

### PR DESCRIPTION
**Pull request by kilahm**
This is useful as a clean up step at the end of individual unit tests.

I am looking at using your library to mock some server requests, but I would like to ensure that each test has a well defined set of route handlers.

### CODE REVIEW

**Comment by A** [comment]
@kilahm awesome! Can you add few words about `clearRoutes` to readme?

**Comment by A** [comment]
ping @kilahm

**Comment by kilahm** [comment]
Do you have comments for the documentation I added?

**Comment by A** [comment]
Nope! That's cool :D

**Comment by A** [comment]
@kilahm published with `0.2.0`

**Pull request merged**
